//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarrisonButler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceWebUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWebUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarrisonButler.ResourceWebUI", typeof(ResourceWebUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var g_garrison_followers = {
        ///    &quot;32&quot;: {
        ///        &quot;id&quot;: 32,
        ///        &quot;source&quot;: 4,
        ///        &quot;quality&quot;: 2,
        ///        &quot;level&quot;: 90,
        ///        &quot;itemlevelarmor&quot;: 600,
        ///        &quot;itemlevelweapon&quot;: 600,
        ///        &quot;alliance&quot;: {
        ///            &quot;npc&quot;: 79607,
        ///            &quot;race&quot;: 15,
        ///            &quot;name&quot;: &quot;Dagg&quot;,
        ///            &quot;classs&quot;: &quot;Subtlety Rogue&quot;,
        ///            &quot;classid&quot;: 28,
        ///            &quot;baseclass&quot;: 4,
        ///            &quot;portrait&quot;: &quot;followerportrait_55124&quot;,
        ///            &quot;abilities&quot;: [104]
        ///        },
        ///        &quot;horde&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string follower_data {
            get {
                return ResourceManager.GetString("follower_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.general-tab&apos;, [&apos;ngMaterial&apos;, &apos;uiSwitch&apos;])
        ///
        ///    .controller(&apos;GeneralOptionsController&apos;, function ($scope) {
        ///
        ///        // Represents a variable name, a title and a description
        ///        $scope.Entry = function Entry(variableName, label, description, displayicon) {
        ///            this.variableName = variableName;
        ///            this.value = false;
        ///            this.label = label;
        ///            this.description = desc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general_tab_module_js {
            get {
                return ResourceManager.GetString("general_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.mailing-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;, &apos;smart-table&apos;, &apos;xeditable&apos;])
        ///
        ///    .controller(&apos;mailingListController&apos;, function ($scope) {
        ///
        ///        // Represents a mail item
        ///        $scope.MailItem = function(itemId, recipient, condition, value, comment) {
        ///            this.itemId = itemId;
        ///            this.recipient = recipient;
        ///            this.condition = condition;
        ///            this.value = value;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mailing_tab_module_js {
            get {
                return ResourceManager.GetString("mailing_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* TABS */
        ///
        ///.nav-tabs{
        ///    background-color: rgb(33,150,243);
        ///}
        ///.ng-isolate-scope a{
        ///    color: #ffffff;
        ///}
        ///.ng-isolate-scope .active a{
        ///    color: black;
        ///}
        ///
        ///.sectionBackground {
        ///    background: rgba(26, 76, 84, 0.16);
        ///    border-radius: 3px;
        ///    margin: 1em;
        ///    padding-bottom: 0px;
        ///    width: 250px!important;
        ///}
        ///.sectionBackground-work-order {
        ///     background: rgba(26, 76, 84, 0.16);
        ///     border-radius: 3px;
        ///     margin: 1em;
        ///     padding-bottom: 0px;
        ///     width: 320px!important;
        /// } [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainUI_css {
            get {
                return ResourceManager.GetString("mainUI_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html ng-app=&quot;GarrisonButlerApp&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GarrisonButler&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimal-ui&quot; /&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;yes&quot; /&gt;
        ///
        ///    &lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainUI_html {
            get {
                return ResourceManager.GetString("mainUI_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angular.module(&apos;GarrisonButlerApp&apos;,
        ///    [
        ///        &apos;ui.bootstrap&apos;,
        ///        &apos;GarrisonButlerApp.general-tab&apos;,
        ///        &apos;GarrisonButlerApp.work-order-tab&apos;,
        ///        &apos;GarrisonButlerApp.profession-tab&apos;,
        ///        &apos;GarrisonButlerApp.milling-tab&apos;,
        ///        &apos;GarrisonButlerApp.mailing-tab&apos;,
        ///        &apos;GarrisonButlerApp.trading-post-tab&apos;,
        ///        &apos;GarrisonButlerApp.missions-tab&apos;,
        ///    ]);
        ///
        ///angular.module(&apos;GarrisonButlerApp&apos;).controller(&apos;MainController&apos;, function ($scope, $window) {
        ///    $scope.butlerSettings = {}; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainUI_js {
            get {
                return ResourceManager.GetString("mainUI_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.milling-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;, &apos;smart-table&apos;])
        ///
        ///    .controller(&apos;millingListController&apos;, function ($scope) {
        ///
        ///        console.log(&quot;test00&quot;);
        ///        // Represents a Item
        ///        $scope.MillingItem = function(itemId, name, activated) {
        ///            this.itemId = itemId;
        ///            this.itemName = name;
        ///            this.activated = activated;
        ///        };
        ///
        ///        try
        ///        {
        ///            con [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string milling_tab_module_js {
            get {
                return ResourceManager.GetString("milling_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Gronnlings Abound&quot;,
        ///    &quot;description&quot;: &quot;Gronnlings are a menace to the region.  We should partner with the Frostwolf clan to thin the population.  One may even join our cause...&quot;,
        ///    &quot;duration&quot;: 1800,
        ///    &quot;level&quot;: 90,
        ///    &quot;itemlevel&quot;: 0,
        ///    &quot;rare&quot;: &quot;&quot;,
        ///    &quot;mechanictype&quot;: &quot;Snow&quot;,
        ///    &quot;missiontype&quot;: &quot;Combat&quot;
        ///}, {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Landfall Recovery&quot;,
        ///    &quot;description&quot;: &quot;It would be a worthwhile endeavor to search the ship we escaped Tanaan Jungle in, it&apos;s b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mission_data {
            get {
                return ResourceManager.GetString("mission_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 3/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.missions-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;, &apos;smart-table&apos;])
        ///
        ///    .controller(&apos;missionsListController&apos;, function ($scope) {
        ///        // Represents a Item
        ///        $scope.missionSetting = function(itemId, name, activated) {
        ///            this.itemId = itemId;
        ///            this.itemName = name;
        ///            this.activated = activated;
        ///        };
        ///
        ///        $scope.color = {
        ///            red: Math.floor(Math.random()  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string missions_tab_module_js {
            get {
                return ResourceManager.GetString("missions_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.profession-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;, &apos;smart-table&apos;])
        ///
        ///    .controller(&apos;professionsListController&apos;, function ($scope) {
        ///
        ///        // Represents a dailyCD
        ///        $scope.Daily = function Daily(itemId, name, profession, activated) {
        ///            this.itemId = itemId;
        ///            this.name = name;
        ///            this.profession = profession;
        ///            this.activated = activated;
        ///        };
        ///        try        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string profession_tab_module_js {
            get {
                return ResourceManager.GetString("profession_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by CoffeeScript 1.7.1
        ///(function() {
        ///    var MODULE_NAME, SLIDER_TAG, angularize, contain, events, gap, halfWidth, hide, module, offset, offsetLeft, pixelize, qualifiedDirectiveDefinition, roundStep, show, sliderDirective, width;
        ///
        ///    MODULE_NAME = &apos;ui.slider&apos;;
        ///
        ///    SLIDER_TAG = &apos;slider&apos;;
        ///
        ///    angularize = function(element) {
        ///        return angular.element(element);
        ///    };
        ///
        ///    pixelize = function(position) {
        ///        return &quot;&quot; + position + &quot;px&quot;;
        ///    };
        ///
        ///    hide = function(elemen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slider_js {
            get {
                return ResourceManager.GetString("slider_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * @version 1.4.9
        /// * @license MIT
        /// */
        ///!function (t, e) {
        ///    &quot;use strict&quot;;
        ///    t.module(&quot;smart-table&quot;, []).run([&quot;$templateCache&quot;, function (t) {
        ///        t.put(&quot;template/smart-table/pagination.html&quot;, &apos;&lt;div class=&quot;pagination&quot; ng-if=&quot;pages.length &gt;= 2&quot;&gt;&lt;ul class=&quot;pagination&quot;&gt;&lt;li ng-repeat=&quot;page in pages&quot; ng-class=&quot;{active: page==currentPage}&quot;&gt;&lt;a ng-click=&quot;selectPage(page)&quot;&gt;{{page}}&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;/div&gt;&apos;)
        ///    }]), t.module(&quot;smart-table&quot;).controller(&quot;stTableController&quot;, [&quot;$scope&quot;, &quot;$parse&quot;, &quot;$filter&quot;, &quot;$attrs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string smart_table_min {
            get {
                return ResourceManager.GetString("smart_table_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/18/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.trading-post-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;, &apos;smart-table&apos;])
        ///
        ///    .controller(&apos;tradingPostListController&apos;, function ($scope) {
        ///        // Represents a Item
        ///        $scope.TPItem = function(itemId, name, activated) {
        ///            this.itemId = itemId;
        ///            this.itemName = name;
        ///            this.activated = activated;
        ///        };
        ///
        ///        try
        ///        {
        ///            var tradingItems = JSON.parse($s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string trading_post_module {
            get {
                return ResourceManager.GetString("trading_post_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * Created by Mickaël on 2/1/2015.
        /// */
        ///
        ///// General Tab
        ///angular.module(&apos;GarrisonButlerApp.work-order-tab&apos;, [&apos;ngMaterial&apos;, &apos;ngAria&apos;,&apos;smart-table&apos;, &apos;ui.slider&apos;])
        ///
        ///    .controller(&apos;buildingsListController&apos;, function ($scope) {
        ///
        ///
        ///        // Load buildings in js value from c# code
        ///        $scope.loadBuildings = function () {
        ///            var res = window.external.getBuildingsJs();
        ///            return res;
        ///        };
        ///        // Represents a building
        ///        $scope.Building = function Building(id, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string work_order_tab_module_js {
            get {
                return ResourceManager.GetString("work_order_tab_module_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///angular-xeditable - 0.1.8
        ///Edit-in-place for angular.js
        ///Build date: 2014-01-10 
        ///*/
        ///
        ///.editable-wrap{display:inline-block;white-space:nowrap;margin:0}.editable-wrap .editable-controls,.editable-wrap .editable-error{margin-bottom:0}.editable-wrap .editable-controls&gt;input,.editable-wrap .editable-controls&gt;select,.editable-wrap .editable-controls&gt;textarea{margin-bottom:0}.editable-wrap .editable-input{display:inline-block}.editable-buttons{display:inline-block;vertical-align:top}.editable-buttons button{margi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xeditable_css {
            get {
                return ResourceManager.GetString("xeditable_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///angular-xeditable - 0.1.8
        ///Edit-in-place for angular.js
        ///Build date: 2014-01-10 
        ///*/
        ///angular.module(&quot;xeditable&quot;,[]).value(&quot;editableOptions&quot;,{theme:&quot;default&quot;,buttons:&quot;right&quot;,blurElem:&quot;cancel&quot;,blurForm:&quot;ignore&quot;,activate:&quot;focus&quot;}),angular.module(&quot;xeditable&quot;).directive(&quot;editableBsdate&quot;,[&quot;editableDirectiveFactory&quot;,function(a){return a({directiveName:&quot;editableBsdate&quot;,inputTpl:&apos;&lt;input type=&quot;text&quot;&gt;&apos;})}]),angular.module(&quot;xeditable&quot;).directive(&quot;editableBstime&quot;,[&quot;editableDirectiveFactory&quot;,function(a){return a({direct [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xeditable_min_js {
            get {
                return ResourceManager.GetString("xeditable_min_js", resourceCulture);
            }
        }
    }
}
