//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarrisonButler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesWebUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesWebUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarrisonButler.ResourcesWebUI", typeof(ResourcesWebUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// AngularJS v1.3.9
        /// (c) 2010-2014 Google, Inc. http://angularjs.org
        /// License: MIT
        ///*/
        ///(function(M,Y,t){&apos;use strict&apos;;function T(b){return function(){var a=arguments[0],c;c=&quot;[&quot;+(b?b+&quot;:&quot;:&quot;&quot;)+a+&quot;] http://errors.angularjs.org/1.3.9/&quot;+(b?b+&quot;/&quot;:&quot;&quot;)+a;for(a=1;a&lt;arguments.length;a++){c=c+(1==a?&quot;?&quot;:&quot;&amp;&quot;)+&quot;p&quot;+(a-1)+&quot;=&quot;;var d=encodeURIComponent,e;e=arguments[a];e=&quot;function&quot;==typeof e?e.toString().replace(/ \{[\s\S]*$/,&quot;&quot;):&quot;undefined&quot;==typeof e?&quot;undefined&quot;:&quot;string&quot;!=typeof e?JSON.stringify(e):e;c+=d(e)}return Error(c)}} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string angular_min {
            get {
                return ResourceManager.GetString("angular_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// AngularJS v1.3.9
        /// (c) 2010-2014 Google, Inc. http://angularjs.org
        /// License: MIT
        ///*/
        ///(function(p,d,C){&apos;use strict&apos;;function v(r,h,g){return{restrict:&quot;ECA&quot;,terminal:!0,priority:400,transclude:&quot;element&quot;,link:function(a,c,b,f,y){function z(){k&amp;&amp;(g.cancel(k),k=null);l&amp;&amp;(l.$destroy(),l=null);m&amp;&amp;(k=g.leave(m),k.then(function(){k=null}),m=null)}function x(){var b=r.current&amp;&amp;r.current.locals;if(d.isDefined(b&amp;&amp;b.$template)){var b=a.$new(),f=r.current;m=y(b,function(b){g.enter(b,null,m||c).then(function(){!d.isDefi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string angular_route_min {
            get {
                return ResourceManager.GetString("angular_route_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face{font-family:FontAwesome;src:url(../fonts/fontawesome-webfont.eot?v=4.2.0);src:url(../fonts/fontawesome-webfont.eot?#iefix&amp;v=4.2.0) format(&apos;embedded-opentype&apos;),url(../fonts/fontawesome-webfont.woff?v=4.2.0) format(&apos;woff&apos;),url(../fonts/fontawesome-webfont.ttf?v=4.2.0) format(&apos;truetype&apos;),url(../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular) format(&apos;svg&apos;);font-weight:400;font-style:normal}.fa{display:inline-block;font:normal normal normal 14px/1 FontAwesome;font-size:inherit;text-rendering [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_base_min {
            get {
                return ResourceManager.GetString("mobile_angular_ui_base_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @media (min-width:992px){.col-md-1,.col-md-10,.col-md-11,.col-md-12,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9{float:left}.col-md-12{width:100%}.col-md-11{width:91.66666667%}.col-md-10{width:83.33333333%}.col-md-9{width:75%}.col-md-8{width:66.66666667%}.col-md-7{width:58.33333333%}.col-md-6{width:50%}.col-md-5{width:41.66666667%}.col-md-4{width:33.33333333%}.col-md-3{width:25%}.col-md-2{width:16.66666667%}.col-md-1{width:8.33333333%}.col-md-pull-12{right:100%}.col-md-pul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_desktop_min {
            get {
                return ResourceManager.GetString("mobile_angular_ui_desktop_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a:hover{outline:0;color:#0055b3;text-decoration:underline}a.text-primary:hover{color:#0062cc}a.text-success:hover{color:#2b542c}a.text-info:hover{color:#245269}a.text-warning:hover{color:#66512c}a.text-danger:hover{color:#843534}a.bg-primary:hover{background-color:#0062cc}a.bg-success:hover{background-color:#c1e2b3}a.bg-info:hover{background-color:#afd9ee}a.bg-warning:hover{background-color:#f7ecb5}a.bg-danger:hover{background-color:#e4b9b9}.table-hover&gt;tbody&gt;tr:hover&gt;td,.table-hover&gt;tbody&gt;tr:hover&gt;th{backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_hover_min {
            get {
                return ResourceManager.GetString("mobile_angular_ui_hover_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function FastClick(a,b){&quot;use strict&quot;;function c(a,b){return function(){return a.apply(b,arguments)}}var d;if(b=b||{},this.trackingClick=!1,this.trackingClickStart=0,this.targetElement=null,this.touchStartX=0,this.touchStartY=0,this.lastTouchIdentifier=0,this.touchBoundary=b.touchBoundary||10,this.layer=a,this.tapDelay=b.tapDelay||200,!FastClick.notNeeded(a)){for(var e=[&quot;onMouse&quot;,&quot;onClick&quot;,&quot;onTouchStart&quot;,&quot;onTouchMove&quot;,&quot;onTouchEnd&quot;,&quot;onTouchCancel&quot;],f=this,g=0,h=e.length;h&gt;g;g++)f[e[g]]=c(f[e[g]],f);deviceIsAn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_min {
            get {
                return ResourceManager.GetString("mobile_angular_ui_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;!--&lt;script src=&quot;http://ajax.googleapis.com/ajax/libs/angularjs/1.2.16/angular.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.12.0.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;https://code.jquery.com/jquery-2.1.3.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;link href=&quot;http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;/&gt;
        ///
        ///    &lt;link href=&quot;./Config/Libraries/BootstrapSwitch/css/bootstrap-switch.css&quot; rel=&quot;stylesheet&quot;&gt;--&gt;
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //angular.module(&apos;ui.bootstrap.demo&apos;, [&apos;ui.bootstrap&apos;]);
        /////angular.module(&apos;ui.bootstrap.demo&apos;).controller(&apos;AccordionDemoCtrl&apos;, function ($scope) {
        /////  $scope.oneAtATime = true;
        ///
        /////  $scope.groups = [
        /////    {
        /////      title: &apos;Dynamic Group Header - 1&apos;,
        /////      content: &apos;Dynamic Group Body - 1&apos;
        /////    },
        /////    {
        /////      title: &apos;Dynamic Group Header - 2&apos;,
        /////      content: &apos;Dynamic Group Body - 2&apos;
        /////    }
        /////  ];
        ///
        /////  $scope.items = [&apos;Item 1&apos;, &apos;Item 2&apos;, &apos;Item 3&apos;];
        ///
        /////  $scope.addItem = function()  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
    }
}
