//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarrisonButler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceWebUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWebUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarrisonButler.ResourceWebUI", typeof(ResourceWebUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// AngularJS v1.3.9
        /// (c) 2010-2014 Google, Inc. http://angularjs.org
        /// License: MIT
        ///*/
        ///(function(M,Y,t){&apos;use strict&apos;;function T(b){return function(){var a=arguments[0],c;c=&quot;[&quot;+(b?b+&quot;:&quot;:&quot;&quot;)+a+&quot;] http://errors.angularjs.org/1.3.9/&quot;+(b?b+&quot;/&quot;:&quot;&quot;)+a;for(a=1;a&lt;arguments.length;a++){c=c+(1==a?&quot;?&quot;:&quot;&amp;&quot;)+&quot;p&quot;+(a-1)+&quot;=&quot;;var d=encodeURIComponent,e;e=arguments[a];e=&quot;function&quot;==typeof e?e.toString().replace(/ \{[\s\S]*$/,&quot;&quot;):&quot;undefined&quot;==typeof e?&quot;undefined&quot;:&quot;string&quot;!=typeof e?JSON.stringify(e):e;c+=d(e)}return Error [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string angular_min_js {
            get {
                return ResourceManager.GetString("angular_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// AngularJS v1.3.9
        /// (c) 2010-2014 Google, Inc. http://angularjs.org
        /// License: MIT
        ///*/
        ///(function(p,d,C){&apos;use strict&apos;;function v(r,h,g){return{restrict:&quot;ECA&quot;,terminal:!0,priority:400,transclude:&quot;element&quot;,link:function(a,c,b,f,y){function z(){k&amp;&amp;(g.cancel(k),k=null);l&amp;&amp;(l.$destroy(),l=null);m&amp;&amp;(k=g.leave(m),k.then(function(){k=null}),m=null)}function x(){var b=r.current&amp;&amp;r.current.locals;if(d.isDefined(b&amp;&amp;b.$template)){var b=a.$new(),f=r.current;m=y(b,function(b){g.enter(b,null,m||c).then(function(){!d.i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string angular_route_min_js {
            get {
                return ResourceManager.GetString("angular_route_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var g_garrison_followers = {
        ///	&quot;32&quot;: {
        ///		&quot;id&quot;: 32,
        ///		&quot;source&quot;: 4,
        ///		&quot;quality&quot;: 2,
        ///		&quot;level&quot;: 90,
        ///		&quot;itemlevelarmor&quot;: 600,
        ///		&quot;itemlevelweapon&quot;: 600,
        ///		&quot;alliance&quot;: {
        ///			&quot;npc&quot;: 79607,
        ///			&quot;race&quot;: 15,
        ///			&quot;name&quot;: &quot;Dagg&quot;,
        ///			&quot;classs&quot;: &quot;Subtlety Rogue&quot;,
        ///			&quot;classid&quot;: 28,
        ///			&quot;baseclass&quot;: 4,
        ///			&quot;portrait&quot;: &quot;followerportrait_55124&quot;,
        ///			&quot;abilities&quot;: [104]
        ///		},
        ///		&quot;horde&quot;: {
        ///			&quot;npc&quot;: 79607,
        ///			&quot;race&quot;: 15,
        ///			&quot;name&quot;: &quot;Dagg&quot;,
        ///			&quot;classs&quot;: &quot;Subtlety Rogue&quot;,
        ///			&quot;classid&quot;: 28,
        ///			&quot;baseclass&quot;: 4,
        ///			&quot;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string follower_data {
            get {
                return ResourceManager.GetString("follower_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{
        ///    &quot;id&quot;: 2,
        ///    &quot;name&quot;: &quot;Gronnlings Abound&quot;,
        ///    &quot;description&quot;: &quot;Gronnlings are a menace to the region.  We should partner with the Frostwolf clan to thin the population.  One may even join our cause...&quot;,
        ///    &quot;duration&quot;: 1800,
        ///    &quot;level&quot;: 90,
        ///    &quot;itemlevel&quot;: 0,
        ///    &quot;rare&quot;: &quot;&quot;,
        ///    &quot;mechanictype&quot;: &quot;Snow&quot;,
        ///    &quot;missiontype&quot;: &quot;Combat&quot;
        ///}, {
        ///    &quot;id&quot;: 3,
        ///    &quot;name&quot;: &quot;Landfall Recovery&quot;,
        ///    &quot;description&quot;: &quot;It would be a worthwhile endeavor to search the ship we escaped Tanaan Jungle in, it&apos;s b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mission_data {
            get {
                return ResourceManager.GetString("mission_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face{font-family:FontAwesome;src:url(../fonts/fontawesome-webfont.eot?v=4.2.0);src:url(../fonts/fontawesome-webfont.eot?#iefix&amp;v=4.2.0) format(&apos;embedded-opentype&apos;),url(../fonts/fontawesome-webfont.woff?v=4.2.0) format(&apos;woff&apos;),url(../fonts/fontawesome-webfont.ttf?v=4.2.0) format(&apos;truetype&apos;),url(../fonts/fontawesome-webfont.svg?v=4.2.0#fontawesomeregular) format(&apos;svg&apos;);font-weight:400;font-style:normal}.fa{display:inline-block;font:normal normal normal 14px/1 FontAwesome;font-size:inherit;text-rendering [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_base_min_css {
            get {
                return ResourceManager.GetString("mobile_angular_ui_base_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @media (min-width:992px){.col-md-1,.col-md-10,.col-md-11,.col-md-12,.col-md-2,.col-md-3,.col-md-4,.col-md-5,.col-md-6,.col-md-7,.col-md-8,.col-md-9{float:left}.col-md-12{width:100%}.col-md-11{width:91.66666667%}.col-md-10{width:83.33333333%}.col-md-9{width:75%}.col-md-8{width:66.66666667%}.col-md-7{width:58.33333333%}.col-md-6{width:50%}.col-md-5{width:41.66666667%}.col-md-4{width:33.33333333%}.col-md-3{width:25%}.col-md-2{width:16.66666667%}.col-md-1{width:8.33333333%}.col-md-pull-12{right:100%}.col-md-pul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_desktop_min_css {
            get {
                return ResourceManager.GetString("mobile_angular_ui_desktop_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a:hover{outline:0;color:#0055b3;text-decoration:underline}a.text-primary:hover{color:#0062cc}a.text-success:hover{color:#2b542c}a.text-info:hover{color:#245269}a.text-warning:hover{color:#66512c}a.text-danger:hover{color:#843534}a.bg-primary:hover{background-color:#0062cc}a.bg-success:hover{background-color:#c1e2b3}a.bg-info:hover{background-color:#afd9ee}a.bg-warning:hover{background-color:#f7ecb5}a.bg-danger:hover{background-color:#e4b9b9}.table-hover&gt;tbody&gt;tr:hover&gt;td,.table-hover&gt;tbody&gt;tr:hover&gt;th{backg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_hover_min_css {
            get {
                return ResourceManager.GetString("mobile_angular_ui_hover_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function FastClick(a,b){&quot;use strict&quot;;function c(a,b){return function(){return a.apply(b,arguments)}}var d;if(b=b||{},this.trackingClick=!1,this.trackingClickStart=0,this.targetElement=null,this.touchStartX=0,this.touchStartY=0,this.lastTouchIdentifier=0,this.touchBoundary=b.touchBoundary||10,this.layer=a,this.tapDelay=b.tapDelay||200,!FastClick.notNeeded(a)){for(var e=[&quot;onMouse&quot;,&quot;onClick&quot;,&quot;onTouchStart&quot;,&quot;onTouchMove&quot;,&quot;onTouchEnd&quot;,&quot;onTouchCancel&quot;],f=this,g=0,h=e.length;h&gt;g;g++)f[e[g]]=c(f[e[g]],f);deviceIsAn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mobile_angular_ui_min_js {
            get {
                return ResourceManager.GetString("mobile_angular_ui_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .tabsdemoStaticTabs {
        ///    /*
        ///   * Animation styles
        ///   */ }
        ///  .tabsdemoStaticTabs #tab1-content {
        ///    background-color: #ffffff; }
        ///  .tabsdemoStaticTabs #tab2-content {
        ///    background-color: #ffffff; }
        ///.tabsdemoStaticTabs #tab3-content {
        ///    background-color: #ffffff; }
        ///.tabsdemoStaticTabs #tab4-content {
        ///    background-color: #ffffff; }
        ///  .tabsdemoStaticTabs .tabpanel-container {
        ///    display: block;
        ///    /*position: relative;*/
        ///    background: #ffffff;
        ///    border: 10px solid black;
        ///    overf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_css {
            get {
                return ResourceManager.GetString("test_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///    &lt;title&gt;GarrisonButler&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge,chrome=1&quot; /&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-capable&quot; content=&quot;yes&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimal-ui&quot; /&gt;
        ///    &lt;meta name=&quot;apple-mobile-web-app-status-bar-style&quot; content=&quot;yes&quot; /&gt;
        ///
        ///
        ///    &lt;script src=&quot;./libraries/Angula [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_html {
            get {
                return ResourceManager.GetString("test_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to app = angular.module(&apos;GarrisonButlerApp&apos;,
        ///    [
        ///        &apos;GarrisonButlerApp.general-tab&apos;,
        ///        &apos;GarrisonButlerApp.profession-tab&apos;,
        ///        &apos;GarrisonButlerApp.work-order-tab&apos;,
        ///        &apos;GarrisonButlerApp.mailing-tab&apos;,
        ///        &apos;GarrisonButlerApp.milling-tab&apos;
        ///    ])
        ///
        ///
        ///    .controller(&apos;mainController&apos;, function($scope) {
        ///
        ///        $scope.butlerSettings = {};
        ///
        ///        // Save boolean from js value in c# code
        ///        $scope.saveCSharpBool = function (propertyName, value) {
        ///            window.exter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_js {
            get {
                return ResourceManager.GetString("test_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ui-grid{border:1px solid #d4d4d4;box-sizing:content-box;-webkit-border-radius:0;-moz-border-radius:0;border-radius:0;-webkit-transform:translateZ(0);-moz-transform:translateZ(0);-o-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0)}.ui-grid-vertical-bar{position:absolute;right:0;width:0}.ui-grid-header-cell:not(:last-child) .ui-grid-vertical-bar,.ui-grid-cell:not(:last-child) .ui-grid-vertical-bar{width:1px}.ui-grid-header-cell:not(:last-child) .ui-grid-vertical-bar{background-colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ui_grid_min_css {
            get {
                return ResourceManager.GetString("ui_grid_min_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! ui-grid - v3.0.0-RC.18 - 2014-12-09
        ///* Copyright (c) 2014 ; License: MIT */
        ///!function () { &quot;use strict&quot;; angular.module(&quot;ui.grid.i18n&quot;, []), angular.module(&quot;ui.grid&quot;, [&quot;ui.grid.i18n&quot;]) }(), function () { &quot;use strict&quot;; angular.module(&quot;ui.grid&quot;).constant(&quot;uiGridConstants&quot;, { LOG_DEBUG_MESSAGES: !0, LOG_WARN_MESSAGES: !0, LOG_ERROR_MESSAGES: !0, CUSTOM_FILTERS: /CUSTOM_FILTERS/g, COL_FIELD: /COL_FIELD/g, MODEL_COL_FIELD: /MODEL_COL_FIELD/g, DISPLAY_CELL_TEMPLATE: /DISPLAY_CELL_TEMPLATE/g, TEMPLATE_REGEXP: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ui_grid_min_js {
            get {
                return ResourceManager.GetString("ui_grid_min_js", resourceCulture);
            }
        }
    }
}
